### ISSUE TITLE
Probabilidad de llegada de un cliente

### ISSUE THREAD

**Issue by Torkuno** [mmasias/lasColas#1]
Saludos, tengo una duda:
En la línea 7 del markdown, dice _"la probabilidad de llegada de un cliente nuevo a la cola se estima entre el 0 y el 40% por minuto."_
Eso significa que cada minuto tenemos que crear una nueva probabilidad entre 0 y 40%, y luego calcular si aparece un nuevo cliente con base a esa nueva probabilidad única del minuto?

**Comment by mmasias** [comment]
Exacto: cada minuto evalúas la probabilidad de llegada de un cliente.

**Comment by mmasias** [comment]
@Torkuno : releyendo tu pregunta, voy a reformular mi respuesta (y por consiguiente, el planteamiento de la pregunta) porque creo que puede inducir a confusión. La probabilidad de llegada de un cliente por minuto es del 40%, y no entre 0% y 40% por minuto. Lo he replanteado mejor así, porque no se trata de calcular aleatoriamente una probabilidad entre (0% y 40%) y luego calcular la llegada en base a esa probabilidad recién calculada.

**Comment by Torkuno** [comment]
Muchas gracias por la aclaración!
